### ISSUE TITLE
@Chyroc

### ISSUE THREAD

**Issue by h3z** [h3z/chat#34]
https://github.com/h3z/chat/blob/6b6de98d4c1271bd672c48e0976b1fa81d86c775/src/client/index.js#L44

这个

**Comment by h3z** [comment]
@Chyroc

**Comment by Chyroc** [comment]
这是啥

**Comment by h3z** [comment]
之前可以的原因。  因为之前没指定host port，就直接这样创建的链接。。

**Comment by h3z** [comment]
搞定，删掉地址就行了。默认window.host
